---
swagger: "2.0"
info:
  description: "API for CorpAssist"
  version: "2023-02-06T00:00:01Z"
  title: "SelfService"
schemes:
- "https"
paths:
  /api/{messages+}:
    x-amazon-apigateway-any-method:
      produces:
      - "application/json"
      parameters:
      - name: "messages"
        in: "path"
        required: true
        type: "string"
      responses: {}
      x-amazon-apigateway-integration:
        uri: ${ProcessMessage}
        httpMethod: "POST"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        cacheNamespace: "kp4grr"
        cacheKeyParameters:
        - "method.request.path.messages"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"